version: '1'

services:
  react-front:
    image: postgres-app:dev
    container_name: "frontend"
    ports:
      - "3000:3000"
    links:
      - restapi

  react-backend:
    image: postgres-backend:dev
    env_file:
      - .env
    container_name: "backend"
    expose:
      - 3011
    ports:
      - "3011:3011"
