version: '3.8'


services:
  client:
    build:
      dockerfile: Dockerfile
      context: ./postgres-app
    volumes:
      - /app/node_modules
      - ./postgres-app:/app
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    volumes:
      - /app/node_modules
      - ./server:/app
    env_file:
      - .env
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./proxy
    ports:
      - "3050:80"

